"""empty message

Revision ID: 321e3cfa8534
Revises: 
Create Date: 2019-05-07 20:04:49.562249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321e3cfa8534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_admin',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('blog_name', sa.String(length=150), nullable=True),
    sa.Column('blog_sub_title', sa.String(length=250), nullable=True),
    sa.Column('about', sa.String(length=450), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('blog_post',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('category',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('blog_post')
    op.drop_table('blog_admin')
    # ### end Alembic commands ###
