"""empty message

Revision ID: 5477c35a2a1c
Revises: be89a3470e2c
Create Date: 2019-05-08 14:23:40.588951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5477c35a2a1c'
down_revision = 'be89a3470e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('blog_name', sa.String(length=150), nullable=True),
    sa.Column('blog_sub_title', sa.String(length=250), nullable=True),
    sa.Column('about', sa.String(length=450), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post')
    op.drop_table('blog_category')
    op.drop_table('blog_admin')
    # ### end Alembic commands ###
