"""empty message

Revision ID: 6cfce45bf9e1
Revises: 7d3a0c035635
Create Date: 2019-05-10 12:03:05.873590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfce45bf9e1'
down_revision = '7d3a0c035635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_admin', sa.Column('blog_subtitle', sa.String(length=250), nullable=True))
    op.drop_column('blog_admin', 'blog_sub_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_admin', sa.Column('blog_sub_title', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('blog_admin', 'blog_subtitle')
    # ### end Alembic commands ###
