"""empty message

Revision ID: 7d3a0c035635
Revises: c1d0c6de0e7d
Create Date: 2019-05-08 21:29:31.638767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3a0c035635'
down_revision = 'c1d0c6de0e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('replied_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog_comment', 'blog_comment', ['replied_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_comment', type_='foreignkey')
    op.drop_column('blog_comment', 'replied_id')
    # ### end Alembic commands ###
