"""empty message

Revision ID: be89a3470e2c
Revises: 321e3cfa8534
Create Date: 2019-05-08 14:16:26.398768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be89a3470e2c'
down_revision = '321e3cfa8534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_admin', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('blog_admin', 'id_')
    op.add_column('blog_category', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint(None, 'blog_category', ['name'])
    op.drop_column('blog_category', 'id_')
    op.add_column('blog_post', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('blog_post', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_foreign_key(None, 'blog_post', 'blog_category', ['category_id'], ['id'])
    op.drop_column('blog_post', 'id_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('id_', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'blog_post', type_='foreignkey')
    op.drop_column('blog_post', 'id')
    op.drop_column('blog_post', 'category_id')
    op.add_column('blog_category', sa.Column('id_', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'blog_category', type_='unique')
    op.drop_column('blog_category', 'id')
    op.add_column('blog_admin', sa.Column('id_', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('blog_admin', 'id')
    # ### end Alembic commands ###
