"""empty message

Revision ID: dc548a19e62c
Revises: 6cfce45bf9e1
Create Date: 2019-05-12 22:21:43.561747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc548a19e62c'
down_revision = '6cfce45bf9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_admin', sa.Column('password', sa.String()))
    op.drop_column('blog_admin', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_admin', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False))
    op.drop_column('blog_admin', 'password')
    # ### end Alembic commands ###
